### ISSUE TITLE
Best View Q3 Winner

### ISSUE THREAD

**Issue by andywalker25** [JoeHalsallOrigin/SocialMedia#18]
Create content

**Comment by JoeHalsallOrigin** [comment]
Shortlist entrants. Select winner. Post on FB & Twitter & Pinterest

**Comment by andywalker25** [comment]
FB post currently running, need to send JL vouchers to winner

**Comment by andywalker25** [comment]
![image](https://user-images.githubusercontent.com/32301748/31272761-f9456b3e-aa83-11e7-9500-e276954f1ac9.png)

Video Slideshow - Reaction video (new idea to vote)

**Comment by andywalker25** [comment]
![image](https://user-images.githubusercontent.com/32301748/31334684-316db5d8-ace7-11e7-8bd5-1065ff9e1586.png)

we have a winner - vouchers sent - closing ticket
