### ISSUE TITLE
Installation of the month winner

### ISSUE THREAD

**Issue by andywalker25** [JoeHalsallOrigin/SocialMedia#19]
create content / edit entrance page

**Comment by JoeHalsallOrigin** [comment]
JH To send e-mail out

**Comment by JoeHalsallOrigin** [comment]
Alter e-mail to show previous winner. Send 1st of over month. Create calendar diary entry to remind us.

**Comment by JoeHalsallOrigin** [comment]
BDMs to take picture with winner if possible. Post/give vouchers to the BDM to deliver where possible.

**Comment by JoeHalsallOrigin** [comment]
AW to speak to AB about the above comment

**Comment by andywalker25** [comment]
VOTE sent to team

**Comment by andywalker25** [comment]
hannah from HBD sending project details for website

**Comment by andywalker25** [comment]
done and closing

**Comment by andywalker25** [comment]
Tracking number: KX 44653997 1GB
