### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by andywalker25** [JoeHalsallOrigin/SocialMedia#4]
No Case Studies Posted In September

**Comment by andywalker25** [comment]
2 have been posted by MWP - Adam is changing pictures

**Comment by JoeHalsallOrigin** [comment]
What's the plan for the case studies? Are they good enough to post as an ad or just boosted posts?

Probably prefer the Susan Streets case study.

**Comment by andywalker25** [comment]
AB is editing now, best view will be going live today/tomorrow so case study will be next week but cracking the whip to make sure it gets done

**Comment by andywalker25** [comment]
Posting w/c 9th October

**Comment by andywalker25** [comment]
sorted
